[env:weigh-station]
platform  = espressif32
board     = sparkfun_esp32s3_thing_plus
framework = arduino

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3        ; verbose ESP-IDF log output during development

lib_deps =
    https://github.com/ATrappmann/PN5180-Library.git
    sparkfun/SparkFun NAU7802 Qwiic Scale Arduino Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    adafruit/Adafruit NeoPixel
    bblanchon/ArduinoJson
    tzapu/WiFiManager
    intel/tinycbor
