[env:weigh-station]
platform  = espressif32
board     = sparkfun_esp32s3_thing_plus
framework = arduino

monitor_speed = 115200

extra_scripts = pre:scripts/pre_tinycbor.py

build_flags =
    -DCORE_DEBUG_LEVEL=3        ; verbose ESP-IDF log output during development
    -DUSER_SETUP_LOADED         ; tells TFT_eSPI to use include/User_Setup.h

lib_deps =
    https://github.com/ATrappmann/PN5180-Library.git
    https://github.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library.git
    bodmer/TFT_eSPI
    adafruit/Adafruit NeoPixel
    bblanchon/ArduinoJson
    tzapu/WiFiManager
    https://github.com/intel/tinycbor.git
