#!/usr/bin/env python3
"""Slice the product matcher out of the firmware so it can be tested natively.

The PlatformIO registry is blocked from the sandbox, so nothing in src/ is
compile-verified there. The matching ladder is worth an exception: it decides
whether two spools are the same product, and getting it wrong is silent —
either the inventory lists one filament twice, or two different filaments merge
into one row and the reorder threshold covers the wrong thing.

This EXTRACTS the real source text rather than restating it, so the test cannot
drift away from the code the way a hand-written copy would. If store.cpp is
refactored such that the markers below no longer bracket the matcher, this
fails loudly at extraction time instead of quietly testing something stale.

Usage (from this directory):
    python3 extract_match.py
    g++ -std=c++17 -O1 -g -fsanitize=address,undefined -o match_test match_test.cpp
    LD_PRELOAD=$(gcc -print-file-name=libasan.so) ./match_test
"""
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "src")


def slice_between(txt, start, end, what):
    i = txt.find(start)
    if i < 0:
        sys.exit("extract: cannot find start of %s (%r)" % (what, start))
    j = txt.find(end, i)
    if j < 0:
        sys.exit("extract: cannot find end of %s (%r)" % (what, end))
    return txt[i:j]


def main():
    h = open(os.path.join(ROOT, "store.h")).read()
    c = open(os.path.join(ROOT, "store.cpp")).read()

    prod = slice_between(h, "struct ProductRecord {", "\n};", "ProductRecord") + "\n};\n"
    match = slice_between(c, "static bool normEq_", "bool storeFindProduct", "matchers")

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "match_extract.h")
    with open(out, "w") as f:
        f.write("// GENERATED by extract_match.py — sliced verbatim out of\n"
                "// src/store.h and src/store.cpp. Do not edit; edit those.\n"
                "#pragma once\n"
                "#include <stdint.h>\n#include <stddef.h>\n#include <string.h>\n"
                "#include <strings.h>\n#include <ctype.h>\n#include <math.h>\n"
                "#include <vector>\n\n"
                + prod
                + "\nstatic std::vector<ProductRecord> sProducts;\n\n"
                + match)
    sys.stderr.write("extracted ProductRecord (%d B) + matchers (%d B) -> %s\n"
                     % (len(prod), len(match), os.path.basename(out)))


if __name__ == "__main__":
    main()
