Import("env")
import os

# tinycbor requires tinycbor-export.h, which is normally generated by CMake.
# PlatformIO clones the raw source without running CMake, so we generate it here.
# On Arduino/embedded targets, all the visibility macros expand to nothing.

libdeps_dir = env.subst("$PROJECT_LIBDEPS_DIR")
env_name = env.subst("$PIOENV")
tinycbor_src = os.path.join(libdeps_dir, env_name, "tinycbor", "src")
export_h = os.path.join(tinycbor_src, "tinycbor-export.h")

if not os.path.exists(export_h):
    os.makedirs(tinycbor_src, exist_ok=True)
    with open(export_h, "w") as f:
        f.write("""\
#ifndef TINYCBOR_EXPORT_H
#define TINYCBOR_EXPORT_H

#define TINYCBOR_EXPORT
#define TINYCBOR_NO_EXPORT
#define TINYCBOR_DEPRECATED
#define TINYCBOR_DEPRECATED_EXPORT
#define TINYCBOR_DEPRECATED_NO_EXPORT

#endif /* TINYCBOR_EXPORT_H */
""")
    print("Generated tinycbor-export.h")
